let activeScope='guest',stateStamp='',mutationSeq=0;
const cloudInfo={user:null,client:null,status:'Локальный режим',busy:false,working:false,dirty:false,revision:0,conflict:false,error:'',ready:false,recovery:false};
const blankState=()=>({version:3,entries:[],timers:[],cars:[],rentals:[]});
const scopedKey=()=> 'maxi.v3.'+activeScope;
function loadLocalScope(){let v=null;try{v=JSON.parse(localStorage.getItem(scopedKey()))}catch{}stateStamp=v?.stamp||'';cloudInfo.revision=v?.revision||0;cloudInfo.dirty=!!v?.dirty;if(v?.state){try{return validateState(v.state)}catch{cloudInfo.error='Не удалось прочитать сохранение. Скачай резервную копию перед восстановлением.'}}if(activeScope==='guest'){try{return validateState({version:1,entries:JSON.parse(localStorage.getItem('maxi.entries'))||[],timers:JSON.parse(localStorage.getItem('maxi.timers'))||[]})}catch{}}return blankState()}
function stateSnapshot(){return JSON.parse(JSON.stringify({version:3,entries,timers,cars,rentals}))}
function applyState(v){const s=validateState(v);entries=s.entries;timers=s.timers;cars=s.cars;rentals=s.rentals;mutationSeq++}
function canEdit(show=true){let blocked=cloudInfo.busy||cloudInfo.conflict;if(!blocked){try{const stored=JSON.parse(localStorage.getItem(scopedKey()));if(stored&&stored.stamp!==stateStamp){blocked=true;if(!cloudInfo.dirty){applyState(stored.state);stateStamp=stored.stamp;cloudInfo.revision=stored.revision||0;cloudInfo.dirty=!!stored.dirty;render()}else cloudInfo.conflict=true}}catch{}}if(blocked&&show)toast(cloudInfo.conflict?'Сначала разреши конфликт в разделе «Аккаунт».':'Данные обновляются. Повтори действие через секунду.');return !blocked}
function saveLocal(markDirty=true){if(markDirty){mutationSeq++;if(cloudInfo.user)cloudInfo.dirty=true}stateStamp=crypto.randomUUID();try{localStorage.setItem(scopedKey(),JSON.stringify({state:stateSnapshot(),revision:cloudInfo.revision,dirty:cloudInfo.dirty,stamp:stateStamp}));return true}catch{toast('Не удалось сохранить в браузере. Скачай резервную копию.');return false}}
function persistState(){saveLocal(true);if(cloudInfo.user&&!cloudInfo.conflict){cloudInfo.status='Ожидает синхронизации';refreshAccountBadge();queueCloudSync()}}
function validateState(o){if(!o||![1,3].includes(o.version)||!Array.isArray(o.entries)||!Array.isArray(o.timers))throw Error('Неподдерживаемое сохранение');const s={version:3,entries:o.entries,timers:o.timers,cars:o.version===1?[]:o.cars,rentals:o.version===1?[]:o.rentals};if(!Array.isArray(s.cars)||!Array.isArray(s.rentals))throw Error('Неполное сохранение');const id=x=>typeof x==='string'&&/^[\w-]{1,100}$/.test(x),str=(x,n)=>typeof x==='string'&&x.length<=n,amount=x=>Number.isSafeInteger(x)&&Math.abs(x)<=1e12,date=x=>Number.isFinite(x)&&x>=0&&x<8640000000000000;for(const a of Object.values(s).filter(Array.isArray)){if(a.length>20000||new Set(a.map(x=>x.id)).size!==a.length)throw Error('Дубликаты или слишком много записей')}
if(!s.entries.every(e=>id(e.id)&&str(e.description,200)&&str(e.job,80)&&amount(e.amount)&&amount(e.fee)&&e.fee>=0&&typeof e.date==='string'&&Number.isFinite(Date.parse(e.date))&&(!e.carId||id(e.carId))&&(!e.rentalId||id(e.rentalId))))throw Error('Некорректные операции');
if(!s.timers.every(t=>id(t.id)&&str(t.name,80)&&date(t.end)&&Number.isFinite(t.duration)&&t.duration>0&&t.duration<=86400000&&typeof t.done==='boolean'))throw Error('Некорректные таймеры');
if(!s.cars.every(c=>id(c.id)&&str(c.name,80)&&c.name.trim()&&str(c.plate,30)&&typeof c.archived==='boolean'))throw Error('Некорректные машины');
if(!s.rentals.every(r=>id(r.id)&&id(r.carId)&&id(r.entryId)&&str(r.carName,80)&&date(r.start)&&date(r.end)&&r.end>r.start&&(r.finishedAt===null||date(r.finishedAt))))throw Error('Некорректная аренда');
const carIds=new Set(s.cars.map(c=>c.id)),occupied=new Set();for(const r of s.rentals){const e=s.entries.find(e=>e.id===r.entryId);if(!carIds.has(r.carId)||!e||e.rentalId!==r.id||e.carId!==r.carId||e.amount<0)throw Error('Нарушена связь аренды и оплаты');if(r.finishedAt===null){if(occupied.has(r.carId))throw Error('Две аренды одной машины');occupied.add(r.carId)}}for(const e of s.entries){if(e.carId&&!carIds.has(e.carId))throw Error('Машина не найдена');if(e.rentalId&&!s.rentals.some(r=>r.id===e.rentalId&&r.entryId===e.id))throw Error('Аренда не найдена')}return JSON.parse(JSON.stringify(s))}
window.addEventListener('storage',e=>{if(e.key===scopedKey()){if($('#modal')?.open&&activeScope==='guest'){$('#modal').close();toast('Данные обновлены в другой вкладке. Открой форму заново.')}if($('#modal')?.open){cloudInfo.conflict=true;cloudInfo.status='Другая вкладка изменила данные';refreshAccountBadge();return}const s=loadLocalScope();applyState(s);render();refreshAccountBadge()}});
