function vehicleKey(value){return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function findVehicle(name){const key=vehicleKey(name);return vehicleCatalog.find(v=>vehicleKey(v.name)===key||v.model===key)}
function searchVehicles(query){const key=vehicleKey(query);if(!key)return [];return vehicleCatalog.filter(v=>vehicleKey(v.name+' '+v.model+' '+v.alias).includes(key)).sort((a,b)=>Number(!vehicleKey(a.name).startsWith(key))-Number(!vehicleKey(b.name).startsWith(key))).slice(0,30)}
function vehiclePicture(name,large=false){const v=findVehicle(name);return `<div class="vehicle-picture ${large?'vehicle-large':''}"><span class="vehicle-fallback">${v?'Изображение машины':esc(name.slice(0,2).toUpperCase())}</span>${v?`<img src="https://docs.fivem.net/vehicles/${encodeURIComponent(v.model)}.webp" alt="${esc(v.name)}" loading="lazy" referrerpolicy="no-referrer">`:''}</div>`}
function bindVehicleImages(root=document){root.querySelectorAll('.vehicle-picture img').forEach(img=>{const loaded=()=>{img.previousElementSibling.hidden=true;img.classList.add('loaded')};const failed=()=>{img.previousElementSibling.hidden=false;img.previousElementSibling.textContent='Нет изображения';img.remove()};img.onload=loaded;img.onerror=failed;if(img.complete){if(img.naturalWidth)loaded();else failed()}})}
function bindVehiclePicker(){const input=document.querySelector('#car-name'),list=document.querySelector('#vehicle-options'),preview=document.querySelector('#vehicle-preview');let shown;
 const update=()=>{const matches=searchVehicles(input.value);list.replaceChildren(...matches.map(v=>{const option=document.createElement('option');option.value=v.name;option.label=v.model;return option}));const v=findVehicle(input.value),model=v?.model||'';if(model===shown)return;shown=model;preview.innerHTML=v?vehiclePicture(v.name,true):'';bindVehicleImages(preview)};
 input.addEventListener('input',update);input.addEventListener('change',update);update();
}
